import 'package:flutter/material.dart';

import '../../const/app_common.dart';
import '../../domain/models/image_service_config.dart';
import '../../provider/actions.dart';
import '../../provider/app_provider.dart';

class ImageGenerationSettingsScreen extends StatefulWidget {
  const ImageGenerationSettingsScreen({super.key});
  @override
  State<ImageGenerationSettingsScreen> createState() => _ImageSettingsState();
}

class _ImageSettingsState extends State<ImageGenerationSettingsScreen> {
  final _endpoint = TextEditingController();
  final _username = TextEditingController();
  final _token = TextEditingController();
  late final AppState _state;
  late final ImageServiceConfig _initial;
  bool _enabled = false, _allowRemote = false, _saving = false;
  String? _error;
  int _credentialEpoch = 0;

  @override
  void initState() {
    super.initState();
    _state = AppState.read(context);
    _initial = _state.imageConfig;
    _endpoint.text = _initial.endpoint;
    _username.text = _initial.username;
    _enabled = _initial.enabled;
    _allowRemote = _initial.allowRemote;
    _loadToken();
  }

  Future<void> _loadToken() async {
    final epoch = _credentialEpoch;
    try {
      final token = await _state.imageService.getToken(_initial);
      if (mounted && epoch == _credentialEpoch) _token.text = token ?? '';
    } catch (_) {
      if (mounted && epoch == _credentialEpoch) setState(() => _error = 'Saved credentials could not be read. You can re-enter them before enabling the service.');
    }
  }

  void _addressChanged(String _) {
    _credentialEpoch++;
    _token.clear();
    setState(() {});
  }

  @override
  void dispose() { _endpoint.dispose(); _username.dispose(); _token.dispose(); super.dispose(); }

  Future<void> _save() async {
    final config = ImageServiceConfig(enabled: _enabled, endpoint: _endpoint.text.trim(),
      allowRemote: _allowRemote, username: _username.text.trim());
    setState(() { _saving = true; _error = null; });
    try {
      if (config.enabled) {
        final uri = config.checkedUri();
        if (!config.isOnDevice && (!_initial.enabled || _initial.endpoint != config.endpoint || !_initial.allowRemote)) {
          final confirmed = await showDialog<bool>(context: context, builder: (dialogContext) => AlertDialog(
            title: const Text('Send image prompts outside this device?'),
            content: Text('Image prompts will be sent to ${uri.origin}. They may contain information from your chat explanation or indexed documents. '
                'Only enable a server you trust. Local text generation and technical diagrams remain on this device.'),
            actions: [
              TextButton(onPressed: () => Navigator.pop(dialogContext, false), child: const Text('Cancel')),
              FilledButton(onPressed: () => Navigator.pop(dialogContext, true), child: const Text('Allow')),
            ],
          ));
          if (confirmed != true || !mounted) return;
        }
        await _state.imageService.saveToken(config, _token.text);
      }
      await _state.setImageConfig(config);
      if (mounted) {
        snack(context, config.enabled ? 'Image service enabled. Request an illustration in chat to use it.' : 'Image service disabled. Local diagrams still work offline.');
        Navigator.pop(context);
      }
    } catch (error) {
      if (mounted) setState(() => _error = '$error');
    } finally {
      if (mounted) setState(() => _saving = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final config = ImageServiceConfig(endpoint: _endpoint.text.trim(), allowRemote: _allowRemote);
    return Scaffold(
      appBar: AppBar(title: const Text('Image Generation')),
      body: Center(child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 760), child: ListView(
        padding: const EdgeInsets.all(20), children: [
          const AppCard(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
            Text('Diagrams work locally', style: TextStyle(fontWeight: FontWeight.w700)),
            SizedBox(height: 8),
            Text('Flowcharts, workflows and architecture diagrams are generated by your local language model and rendered by Tapat AI. No image server or network is needed.'),
          ])),
          const SizedBox(height: 16),
          const AppCard(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
            Text('Illustrations need an image model', style: TextStyle(fontWeight: FontWeight.w700)),
            SizedBox(height: 8),
            Text('The GGUF language model generates text, not image pixels. For illustrations, run a Stable Diffusion WebUI-compatible server with an image checkpoint and the --api option. Tapat AI uses its /sdapi/v1/txt2img API.'),
            SizedBox(height: 8),
            Text('A loopback address points to this device, not another computer. For a GPU server on another device, use a trusted HTTPS endpoint. The service and image model are installed separately.'),
          ])),
          const SizedBox(height: 16),
          SwitchListTile(contentPadding: EdgeInsets.zero, title: const Text('Enable illustration generation'),
            subtitle: const Text('Off by default. Only explicit image requests use the service.'), value: _enabled,
            onChanged: _saving ? null : (value) => setState(() => _enabled = value)),
          const SizedBox(height: 12),
          TextField(key: const ValueKey('image-endpoint'), controller: _endpoint, enabled: !_saving,
            keyboardType: TextInputType.url, autocorrect: false, onChanged: _addressChanged,
            decoration: const InputDecoration(labelText: 'Image server address', hintText: 'http://127.0.0.1:7860')),
          const SizedBox(height: 12),
          CheckboxListTile(contentPadding: EdgeInsets.zero, title: const Text('Allow prompts outside this device'),
            subtitle: Text(config.isOnDevice ? 'Not needed for a server on this device.' : 'Required for another device or an external service. HTTPS is mandatory.'),
            value: _allowRemote, onChanged: _saving ? null : (value) => setState(() => _allowRemote = value ?? false)),
          const SizedBox(height: 12),
          TextField(controller: _username, enabled: !_saving, autocorrect: false, onChanged: _addressChanged,
            decoration: const InputDecoration(labelText: 'API username (optional)', helperText: 'For WebUI --api-auth. Leave blank for bearer-token proxies.')),
          const SizedBox(height: 12),
          TextField(key: const ValueKey('image-token'), controller: _token, enabled: !_saving, obscureText: true,
            autocorrect: false, enableSuggestions: false,
            decoration: InputDecoration(labelText: _username.text.trim().isEmpty ? 'Bearer token (optional)' : 'API password',
              helperText: 'Saved securely when enabled; never stored in chat or backups.')),
          if (_error != null) Padding(padding: const EdgeInsets.symmetric(vertical: 12), child: Semantics(liveRegion: true,
            child: Text(_error!, style: TextStyle(color: Theme.of(context).colorScheme.error)))),
          const SizedBox(height: 20),
          GradientButton(label: 'Save', loading: _saving, onPressed: _saving ? null : _save, icon: Icons.save_outlined),
          TextButton(onPressed: _saving ? null : () => Navigator.pop(context), child: const Text('Cancel')),
        ],
      ))),
    );
  }
}
