// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/entities/entities.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6737961018691423622),
    name: 'ChatMessageEntity',
    lastPropertyId: const obx_int.IdUid(6, 2516567131893338788),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7691944923890808891),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4809638087497072681),
        name: 'topicId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 785652801508983482),
        relationField: 'topic',
        relationTarget: 'TopicEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9177192458370206867),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2093319426745688394),
        name: 'isUser',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8172967214626988522),
        name: 'sourcesJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2516567131893338788),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7773285418227808295),
    name: 'ChunkEntity',
    lastPropertyId: const obx_int.IdUid(8, 6309834124675333817),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 793204470697595391),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1003795137650079133),
        name: 'documentId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 146882923296368734),
        relationField: 'document',
        relationTarget: 'DocumentEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8052829267913481880),
        name: 'topicId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 6694921578431953727),
        relationField: 'topic',
        relationTarget: 'TopicEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4884051529145437508),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8579715914938522568),
        name: 'pageNumber',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6022666159796462061),
        name: 'chunkIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8208046485054932079),
        name: 'embeddingModelId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6309834124675333817),
        name: 'vector',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(4, 4845331490722803964),
        hnswParams: obx_int.ModelHnswParams(dimensions: 384, distanceType: 2),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 8222347767563289884),
    name: 'DocumentEntity',
    lastPropertyId: const obx_int.IdUid(12, 7413860099284123178),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 344218089242029455),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 316230646521734737),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(5, 5129767606901929327),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3645573379790760382),
        name: 'topicId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(6, 428904202111550861),
        relationField: 'topic',
        relationTarget: 'TopicEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5615970237355039506),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5083537693362384676),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4252165163123351783),
        name: 'sizeBytes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7258134034761669945),
        name: 'path',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6107855677754132888),
        name: 'pageCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3899325936350026548),
        name: 'chunkCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 9092452993354777738),
        name: 'status',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 2231518639355935142),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 7413860099284123178),
        name: 'contentSha256',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 8934789391569586383),
    name: 'ModelEntity',
    lastPropertyId: const obx_int.IdUid(13, 4635530556854970595),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4242976631845959375),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4851085419314560498),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(7, 2446716876691235364),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3897107457475005976),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6223869740718339161),
        name: 'kind',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3684248030181389320),
        name: 'repoId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3708596323855852942),
        name: 'filename',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2674163790494774888),
        name: 'localPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3580988796877494309),
        name: 'sizeBytes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4172597465638249990),
        name: 'status',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1217299929628093883),
        name: 'isActive',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 1603071678138508968),
        name: 'sha256',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 1509937118587765814),
        name: 'dimensions',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 4635530556854970595),
        name: 'license',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 8842377055169655081),
    name: 'SettingEntity',
    lastPropertyId: const obx_int.IdUid(3, 3469822871632870691),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8425875048980443192),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7182977540736854563),
        name: 'key',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(8, 1791933781202867991),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3469822871632870691),
        name: 'value',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 9087363412720310107),
    name: 'TopicEntity',
    lastPropertyId: const obx_int.IdUid(8, 1372681681481630475),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4676836169047569834),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1746680860491171970),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(9, 996878245076234993),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 663732524889825167),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 9005297686559779209),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3867852049284330561),
        name: 'category',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 10996607896027669),
        name: 'iconIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7710840463913433049),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1372681681481630475),
        name: 'nfcId',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(6, 9087363412720310107),
    lastIndexId: const obx_int.IdUid(9, 996878245076234993),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ChatMessageEntity: obx_int.EntityDefinition<ChatMessageEntity>(
      model: _entities[0],
      toOneRelations: (ChatMessageEntity object) => [object.topic],
      toManyRelations: (ChatMessageEntity object) => {},
      getId: (ChatMessageEntity object) => object.id,
      setId: (ChatMessageEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ChatMessageEntity object, fb.Builder fbb) {
        final textOffset = fbb.writeString(object.text);
        final sourcesJsonOffset = fbb.writeString(object.sourcesJson);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.topic.targetId);
        fbb.addOffset(2, textOffset);
        fbb.addBool(3, object.isUser);
        fbb.addOffset(4, sourcesJsonOffset);
        fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = ChatMessageEntity()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..text = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..isUser = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            10,
            false,
          )
          ..sourcesJson = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
          );
        object.topic.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.topic.attach(store);
        return object;
      },
    ),
    ChunkEntity: obx_int.EntityDefinition<ChunkEntity>(
      model: _entities[1],
      toOneRelations: (ChunkEntity object) => [object.document, object.topic],
      toManyRelations: (ChunkEntity object) => {},
      getId: (ChunkEntity object) => object.id,
      setId: (ChunkEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ChunkEntity object, fb.Builder fbb) {
        final textOffset = fbb.writeString(object.text);
        final embeddingModelIdOffset = fbb.writeString(object.embeddingModelId);
        final vectorOffset = object.vector == null
            ? null
            : fbb.writeListFloat32(object.vector!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.document.targetId);
        fbb.addInt64(2, object.topic.targetId);
        fbb.addOffset(3, textOffset);
        fbb.addInt64(4, object.pageNumber);
        fbb.addInt64(5, object.chunkIndex);
        fbb.addOffset(6, embeddingModelIdOffset);
        fbb.addOffset(7, vectorOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = ChunkEntity()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..text = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..pageNumber = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            12,
            0,
          )
          ..chunkIndex = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            14,
            0,
          )
          ..embeddingModelId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '')
          ..vector = const fb.ListReader<double>(
            fb.Float32Reader(),
            lazy: false,
          ).vTableGetNullable(buffer, rootOffset, 18);
        object.document.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.document.attach(store);
        object.topic.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.topic.attach(store);
        return object;
      },
    ),
    DocumentEntity: obx_int.EntityDefinition<DocumentEntity>(
      model: _entities[2],
      toOneRelations: (DocumentEntity object) => [object.topic],
      toManyRelations: (DocumentEntity object) => {},
      getId: (DocumentEntity object) => object.id,
      setId: (DocumentEntity object, int id) {
        object.id = id;
      },
      objectToFB: (DocumentEntity object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final nameOffset = fbb.writeString(object.name);
        final typeOffset = fbb.writeString(object.type);
        final pathOffset = fbb.writeString(object.path);
        final statusOffset = fbb.writeString(object.status);
        final contentSha256Offset = fbb.writeString(object.contentSha256);
        fbb.startTable(13);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addInt64(2, object.topic.targetId);
        fbb.addOffset(3, nameOffset);
        fbb.addOffset(4, typeOffset);
        fbb.addInt64(5, object.sizeBytes);
        fbb.addOffset(6, pathOffset);
        fbb.addInt64(7, object.pageCount);
        fbb.addInt64(8, object.chunkCount);
        fbb.addOffset(9, statusOffset);
        fbb.addInt64(10, object.createdAt.millisecondsSinceEpoch);
        fbb.addOffset(11, contentSha256Offset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = DocumentEntity()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..uuid = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..type = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..sizeBytes = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            14,
            0,
          )
          ..path = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '')
          ..pageCount = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            18,
            0,
          )
          ..chunkCount = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            20,
            0,
          )
          ..status = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 22, '')
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0),
          )
          ..contentSha256 = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 26, '');
        object.topic.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.topic.attach(store);
        return object;
      },
    ),
    ModelEntity: obx_int.EntityDefinition<ModelEntity>(
      model: _entities[3],
      toOneRelations: (ModelEntity object) => [],
      toManyRelations: (ModelEntity object) => {},
      getId: (ModelEntity object) => object.id,
      setId: (ModelEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ModelEntity object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final nameOffset = fbb.writeString(object.name);
        final kindOffset = fbb.writeString(object.kind);
        final repoIdOffset = fbb.writeString(object.repoId);
        final filenameOffset = fbb.writeString(object.filename);
        final localPathOffset = fbb.writeString(object.localPath);
        final statusOffset = fbb.writeString(object.status);
        final sha256Offset = fbb.writeString(object.sha256);
        final licenseOffset = fbb.writeString(object.license);
        fbb.startTable(14);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, kindOffset);
        fbb.addOffset(4, repoIdOffset);
        fbb.addOffset(5, filenameOffset);
        fbb.addOffset(6, localPathOffset);
        fbb.addInt64(7, object.sizeBytes);
        fbb.addOffset(8, statusOffset);
        fbb.addBool(9, object.isActive);
        fbb.addOffset(10, sha256Offset);
        fbb.addInt64(11, object.dimensions);
        fbb.addOffset(12, licenseOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = ModelEntity()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..uuid = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..kind = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..repoId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..filename = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '')
          ..localPath = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '')
          ..sizeBytes = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            18,
            0,
          )
          ..status = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 20, '')
          ..isActive = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            22,
            false,
          )
          ..sha256 = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 24, '')
          ..dimensions = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            26,
            0,
          )
          ..license = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 28, '');

        return object;
      },
    ),
    SettingEntity: obx_int.EntityDefinition<SettingEntity>(
      model: _entities[4],
      toOneRelations: (SettingEntity object) => [],
      toManyRelations: (SettingEntity object) => {},
      getId: (SettingEntity object) => object.id,
      setId: (SettingEntity object, int id) {
        object.id = id;
      },
      objectToFB: (SettingEntity object, fb.Builder fbb) {
        final keyOffset = fbb.writeString(object.key);
        final valueOffset = fbb.writeString(object.value);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, keyOffset);
        fbb.addOffset(2, valueOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = SettingEntity()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..key = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..value = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '');

        return object;
      },
    ),
    TopicEntity: obx_int.EntityDefinition<TopicEntity>(
      model: _entities[5],
      toOneRelations: (TopicEntity object) => [],
      toManyRelations: (TopicEntity object) => {},
      getId: (TopicEntity object) => object.id,
      setId: (TopicEntity object, int id) {
        object.id = id;
      },
      objectToFB: (TopicEntity object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = fbb.writeString(object.description);
        final categoryOffset = fbb.writeString(object.category);
        final nfcIdOffset = fbb.writeString(object.nfcId);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, descriptionOffset);
        fbb.addOffset(4, categoryOffset);
        fbb.addInt64(5, object.iconIndex);
        fbb.addInt64(6, object.createdAt.millisecondsSinceEpoch);
        fbb.addOffset(7, nfcIdOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = TopicEntity()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..uuid = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..description = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..category = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..iconIndex = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            14,
            0,
          )
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
          )
          ..nfcId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 18, '');

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ChatMessageEntity] entity fields to define ObjectBox queries.
class ChatMessageEntity_ {
  /// See [ChatMessageEntity.id].
  static final id = obx.QueryIntegerProperty<ChatMessageEntity>(
    _entities[0].properties[0],
  );

  /// See [ChatMessageEntity.topic].
  static final topic = obx.QueryRelationToOne<ChatMessageEntity, TopicEntity>(
    _entities[0].properties[1],
  );

  /// See [ChatMessageEntity.text].
  static final text = obx.QueryStringProperty<ChatMessageEntity>(
    _entities[0].properties[2],
  );

  /// See [ChatMessageEntity.isUser].
  static final isUser = obx.QueryBooleanProperty<ChatMessageEntity>(
    _entities[0].properties[3],
  );

  /// See [ChatMessageEntity.sourcesJson].
  static final sourcesJson = obx.QueryStringProperty<ChatMessageEntity>(
    _entities[0].properties[4],
  );

  /// See [ChatMessageEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<ChatMessageEntity>(
    _entities[0].properties[5],
  );
}

/// [ChunkEntity] entity fields to define ObjectBox queries.
class ChunkEntity_ {
  /// See [ChunkEntity.id].
  static final id = obx.QueryIntegerProperty<ChunkEntity>(
    _entities[1].properties[0],
  );

  /// See [ChunkEntity.document].
  static final document = obx.QueryRelationToOne<ChunkEntity, DocumentEntity>(
    _entities[1].properties[1],
  );

  /// See [ChunkEntity.topic].
  static final topic = obx.QueryRelationToOne<ChunkEntity, TopicEntity>(
    _entities[1].properties[2],
  );

  /// See [ChunkEntity.text].
  static final text = obx.QueryStringProperty<ChunkEntity>(
    _entities[1].properties[3],
  );

  /// See [ChunkEntity.pageNumber].
  static final pageNumber = obx.QueryIntegerProperty<ChunkEntity>(
    _entities[1].properties[4],
  );

  /// See [ChunkEntity.chunkIndex].
  static final chunkIndex = obx.QueryIntegerProperty<ChunkEntity>(
    _entities[1].properties[5],
  );

  /// See [ChunkEntity.embeddingModelId].
  static final embeddingModelId = obx.QueryStringProperty<ChunkEntity>(
    _entities[1].properties[6],
  );

  /// See [ChunkEntity.vector].
  static final vector = obx.QueryHnswProperty<ChunkEntity>(
    _entities[1].properties[7],
  );
}

/// [DocumentEntity] entity fields to define ObjectBox queries.
class DocumentEntity_ {
  /// See [DocumentEntity.id].
  static final id = obx.QueryIntegerProperty<DocumentEntity>(
    _entities[2].properties[0],
  );

  /// See [DocumentEntity.uuid].
  static final uuid = obx.QueryStringProperty<DocumentEntity>(
    _entities[2].properties[1],
  );

  /// See [DocumentEntity.topic].
  static final topic = obx.QueryRelationToOne<DocumentEntity, TopicEntity>(
    _entities[2].properties[2],
  );

  /// See [DocumentEntity.name].
  static final name = obx.QueryStringProperty<DocumentEntity>(
    _entities[2].properties[3],
  );

  /// See [DocumentEntity.type].
  static final type = obx.QueryStringProperty<DocumentEntity>(
    _entities[2].properties[4],
  );

  /// See [DocumentEntity.sizeBytes].
  static final sizeBytes = obx.QueryIntegerProperty<DocumentEntity>(
    _entities[2].properties[5],
  );

  /// See [DocumentEntity.path].
  static final path = obx.QueryStringProperty<DocumentEntity>(
    _entities[2].properties[6],
  );

  /// See [DocumentEntity.pageCount].
  static final pageCount = obx.QueryIntegerProperty<DocumentEntity>(
    _entities[2].properties[7],
  );

  /// See [DocumentEntity.chunkCount].
  static final chunkCount = obx.QueryIntegerProperty<DocumentEntity>(
    _entities[2].properties[8],
  );

  /// See [DocumentEntity.status].
  static final status = obx.QueryStringProperty<DocumentEntity>(
    _entities[2].properties[9],
  );

  /// See [DocumentEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<DocumentEntity>(
    _entities[2].properties[10],
  );

  /// See [DocumentEntity.contentSha256].
  static final contentSha256 = obx.QueryStringProperty<DocumentEntity>(
    _entities[2].properties[11],
  );
}

/// [ModelEntity] entity fields to define ObjectBox queries.
class ModelEntity_ {
  /// See [ModelEntity.id].
  static final id = obx.QueryIntegerProperty<ModelEntity>(
    _entities[3].properties[0],
  );

  /// See [ModelEntity.uuid].
  static final uuid = obx.QueryStringProperty<ModelEntity>(
    _entities[3].properties[1],
  );

  /// See [ModelEntity.name].
  static final name = obx.QueryStringProperty<ModelEntity>(
    _entities[3].properties[2],
  );

  /// See [ModelEntity.kind].
  static final kind = obx.QueryStringProperty<ModelEntity>(
    _entities[3].properties[3],
  );

  /// See [ModelEntity.repoId].
  static final repoId = obx.QueryStringProperty<ModelEntity>(
    _entities[3].properties[4],
  );

  /// See [ModelEntity.filename].
  static final filename = obx.QueryStringProperty<ModelEntity>(
    _entities[3].properties[5],
  );

  /// See [ModelEntity.localPath].
  static final localPath = obx.QueryStringProperty<ModelEntity>(
    _entities[3].properties[6],
  );

  /// See [ModelEntity.sizeBytes].
  static final sizeBytes = obx.QueryIntegerProperty<ModelEntity>(
    _entities[3].properties[7],
  );

  /// See [ModelEntity.status].
  static final status = obx.QueryStringProperty<ModelEntity>(
    _entities[3].properties[8],
  );

  /// See [ModelEntity.isActive].
  static final isActive = obx.QueryBooleanProperty<ModelEntity>(
    _entities[3].properties[9],
  );

  /// See [ModelEntity.sha256].
  static final sha256 = obx.QueryStringProperty<ModelEntity>(
    _entities[3].properties[10],
  );

  /// See [ModelEntity.dimensions].
  static final dimensions = obx.QueryIntegerProperty<ModelEntity>(
    _entities[3].properties[11],
  );

  /// See [ModelEntity.license].
  static final license = obx.QueryStringProperty<ModelEntity>(
    _entities[3].properties[12],
  );
}

/// [SettingEntity] entity fields to define ObjectBox queries.
class SettingEntity_ {
  /// See [SettingEntity.id].
  static final id = obx.QueryIntegerProperty<SettingEntity>(
    _entities[4].properties[0],
  );

  /// See [SettingEntity.key].
  static final key = obx.QueryStringProperty<SettingEntity>(
    _entities[4].properties[1],
  );

  /// See [SettingEntity.value].
  static final value = obx.QueryStringProperty<SettingEntity>(
    _entities[4].properties[2],
  );
}

/// [TopicEntity] entity fields to define ObjectBox queries.
class TopicEntity_ {
  /// See [TopicEntity.id].
  static final id = obx.QueryIntegerProperty<TopicEntity>(
    _entities[5].properties[0],
  );

  /// See [TopicEntity.uuid].
  static final uuid = obx.QueryStringProperty<TopicEntity>(
    _entities[5].properties[1],
  );

  /// See [TopicEntity.name].
  static final name = obx.QueryStringProperty<TopicEntity>(
    _entities[5].properties[2],
  );

  /// See [TopicEntity.description].
  static final description = obx.QueryStringProperty<TopicEntity>(
    _entities[5].properties[3],
  );

  /// See [TopicEntity.category].
  static final category = obx.QueryStringProperty<TopicEntity>(
    _entities[5].properties[4],
  );

  /// See [TopicEntity.iconIndex].
  static final iconIndex = obx.QueryIntegerProperty<TopicEntity>(
    _entities[5].properties[5],
  );

  /// See [TopicEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<TopicEntity>(
    _entities[5].properties[6],
  );

  /// See [TopicEntity.nfcId].
  static final nfcId = obx.QueryStringProperty<TopicEntity>(
    _entities[5].properties[7],
  );
}
