-keep class com.write4me.llama_cpp_dart.** { *; }
-keep class ai.onnxruntime.** { *; }
-keep class kotlin.jvm.functions.Function1
-keepclassmembers class * implements kotlin.jvm.functions.Function1 { public java.lang.Object invoke(java.lang.Object); }
-keepclasseswithmembernames class * { native <methods>; }
